name: CI
on:
  push:
    branches-ignore:
      - ssrjson
  pull_request:
    branches-ignore:
      - ssrjson
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ./test.sh
